### ISSUE TITLE
Bound variables getting muddled

### ISSUE THREAD

**Issue by n-arms** [n-arms/lambda-parser#3]
## Description
The following two expressions yield different reductions despite being identical via alpha reduction:
```(λab.ab) (λcd.cd) (λef.ef) = λdf.df``` (correct)
```(λab.ab) (λab.ab) (λab.ab) = λb'b'b.b'b``` (both incorrect and illegal due to identical arguments in 1 function)

The reason for this has to do with the way alpha reduction works. If two identical expressions are on either side of a function, with some variables bound to the function, and some identical variables bound elsewhere, it reduces so that everything (including the bound variables) get changed without getting rebound. This is obviously a huge problem that will require an entire rework of how arguments are dealt with.

## Solution
My plan is the following:
- a new method called bind.
- When bind is called, it starts by calling bind recursively so that the smallest function gets bound first.
- When a function is bound, it adds a new string to a static arraylist for every argument, then recursively searches down its function body. Whenever it finds a variable name that matches, it sets its "identification number" to that of the functions argument.
- When two variables are tested for equality, instead of checking the letter associate with them, it checks the ID code.
- This essentially creates a disjoint set of arguments.
- When a new instance of a combinator is put into a function, it makes a copy, and then calls bind on all of the copies arguments.

## TODO
- [x] associate each argument with a unique code
- [x] compare arguments by code instead of name
- [x] print arguments by name
- [x] figure out how combinator codes work

**Comment by n-arms** [comment]
Bound variables are now working properly. A garbage collection system would be nice to reduce the huge amount of virtual "memory" that gets used up, but that is out of the scope of this issue.
